# Project name
PROJECT: nano

BARCODE_FILE: ../input/fastq_pass/barcode_index.txt
SEQ_SUMMARY: ../input/sequencing_summary.txt
DIR_FASTQ: ../input/fastq_pass
DIR_OUTPUT: ../output/output_20220225_smk

GENOME: ../data/ref/GRCh38.primary_assembly.genome.fa
ANNOTATE: ../data/ref/gencode.v38.annotation.gtf
TRANSCRIPTOME: ../data/ref/gencode.v38.transcripts.fa

DIR_LONGGF: /cluster/projects/p19/Software/nanogf/bin

TX2GENE: ../data/ref/tx2gene_gencode.tsv
ID2SYMBOL: ../data/ref/id2symbol_gencode.tsv

